//
// Created by duyph on 2023-04-26.
//

#ifndef COMP_8042_ADVANCED_ALGORITHMS_AND_DATA_STRUCTURES_DESIGN_AND_ANALYSIS_GISRECORD_H
#define COMP_8042_ADVANCED_ALGORITHMS_AND_DATA_STRUCTURES_DESIGN_AND_ANALYSIS_GISRECORD_H

class GISRecord {

};

#endif //COMP_8042_ADVANCED_ALGORITHMS_AND_DATA_STRUCTURES_DESIGN_AND_ANALYSIS_GISRECORD_H
